package com.example.mycityapp.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF646116)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFECE68D)
val onPrimaryContainerLight = Color(0xFF4C4900)
val secondaryLight = Color(0xFF006A64)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF9DF2E9)
val onSecondaryContainerLight = Color(0xFF00504B)
val tertiaryLight = Color(0xFF2C638B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCCE5FF)
val onTertiaryContainerLight = Color(0xFF084B72)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFEF9EB)
val onBackgroundLight = Color(0xFF1D1C14)
val surfaceLight = Color(0xFFFCFAEC)
val onSurfaceLight = Color(0xFF1C1C14)
val surfaceVariantLight = Color(0xFFE7E3D1)
val onSurfaceVariantLight = Color(0xFF49473A)
val outlineLight = Color(0xFF7A7768)
val outlineVariantLight = Color(0xFFCAC7B5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313128)
val inverseOnSurfaceLight = Color(0xFFF4F1E4)
val inversePrimaryLight = Color(0xFFCFCA74)
val surfaceDimLight = Color(0xFFDDDACD)
val surfaceBrightLight = Color(0xFFFCFAEC)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F4E7)
val surfaceContainerLight = Color(0xFFF1EEE1)
val surfaceContainerHighLight = Color(0xFFEBE8DB)
val surfaceContainerHighestLight = Color(0xFFE5E3D6)

val primaryLightMediumContrast = Color(0xFF3A3800)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF736F24)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF003E3A)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF1A7A73)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF00395A)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF3D719B)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF9EB)
val onBackgroundLightMediumContrast = Color(0xFF1D1C14)
val surfaceLightMediumContrast = Color(0xFFFCFAEC)
val onSurfaceLightMediumContrast = Color(0xFF11120A)
val surfaceVariantLightMediumContrast = Color(0xFFE7E3D1)
val onSurfaceVariantLightMediumContrast = Color(0xFF38372A)
val outlineLightMediumContrast = Color(0xFF555345)
val outlineVariantLightMediumContrast = Color(0xFF706D5F)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF313128)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF4F1E4)
val inversePrimaryLightMediumContrast = Color(0xFFCFCA74)
val surfaceDimLightMediumContrast = Color(0xFFC9C7BA)
val surfaceBrightLightMediumContrast = Color(0xFFFCFAEC)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF7F4E7)
val surfaceContainerLightMediumContrast = Color(0xFFEBE8DB)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDDD0)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD4D2C5)

val primaryLightHighContrast = Color(0xFF302D00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF4E4B00)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF00322F)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF00534E)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF002F4B)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF0D4D74)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF9EB)
val onBackgroundLightHighContrast = Color(0xFF1D1C14)
val surfaceLightHighContrast = Color(0xFFFCFAEC)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE7E3D1)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2E2D21)
val outlineVariantLightHighContrast = Color(0xFF4B4A3C)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF313128)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFCFCA74)
val surfaceDimLightHighContrast = Color(0xFFBBB9AD)
val surfaceBrightLightHighContrast = Color(0xFFFCFAEC)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF4F1E4)
val surfaceContainerLightHighContrast = Color(0xFFE5E3D6)
val surfaceContainerHighLightHighContrast = Color(0xFFD7D5C8)
val surfaceContainerHighestLightHighContrast = Color(0xFFC9C7BA)

val primaryDark = Color(0xFFCFCA74)
val onPrimaryDark = Color(0xFF343200)
val primaryContainerDark = Color(0xFF4C4900)
val onPrimaryContainerDark = Color(0xFFECE68D)
val secondaryDark = Color(0xFF81D5CD)
val onSecondaryDark = Color(0xFF003734)
val secondaryContainerDark = Color(0xFF00504B)
val onSecondaryContainerDark = Color(0xFF9DF2E9)
val tertiaryDark = Color(0xFF99CCFA)
val onTertiaryDark = Color(0xFF003351)
val tertiaryContainerDark = Color(0xFF084B72)
val onTertiaryContainerDark = Color(0xFFCCE5FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF14140C)
val onBackgroundDark = Color(0xFFE6E2D5)
val surfaceDark = Color(0xFF14140C)
val onSurfaceDark = Color(0xFFE5E3D6)
val surfaceVariantDark = Color(0xFF49473A)
val onSurfaceVariantDark = Color(0xFFCAC7B5)
val outlineDark = Color(0xFF949181)
val outlineVariantDark = Color(0xFF49473A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E3D6)
val inverseOnSurfaceDark = Color(0xFF313128)
val inversePrimaryDark = Color(0xFF646116)
val surfaceDimDark = Color(0xFF14140C)
val surfaceBrightDark = Color(0xFF3A3A31)
val surfaceContainerLowestDark = Color(0xFF0E0F08)
val surfaceContainerLowDark = Color(0xFF1C1C14)
val surfaceContainerDark = Color(0xFF202018)
val surfaceContainerHighDark = Color(0xFF2A2A22)
val surfaceContainerHighestDark = Color(0xFF35352C)

val primaryDarkMediumContrast = Color(0xFFE5E087)
val onPrimaryDarkMediumContrast = Color(0xFF292700)
val primaryContainerDarkMediumContrast = Color(0xFF989444)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF97EBE3)
val onSecondaryDarkMediumContrast = Color(0xFF002B28)
val secondaryContainerDarkMediumContrast = Color(0xFF489E97)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFC0E0FF)
val onTertiaryDarkMediumContrast = Color(0xFF002841)
val tertiaryContainerDarkMediumContrast = Color(0xFF6395C1)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF14140C)
val onBackgroundDarkMediumContrast = Color(0xFFE6E2D5)
val surfaceDarkMediumContrast = Color(0xFF14140C)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF49473A)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE1DDCB)
val outlineDarkMediumContrast = Color(0xFFB5B2A1)
val outlineVariantDarkMediumContrast = Color(0xFF939181)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE5E3D6)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2A22)
val inversePrimaryDarkMediumContrast = Color(0xFF4D4A00)
val surfaceDimDarkMediumContrast = Color(0xFF14140C)
val surfaceBrightDarkMediumContrast = Color(0xFF45453C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070803)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1E1E16)
val surfaceContainerDarkMediumContrast = Color(0xFF282820)
val surfaceContainerHighDarkMediumContrast = Color(0xFF33332A)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3E35)

val primaryDarkHighContrast = Color(0xFFFAF499)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFCBC670)
val onPrimaryContainerDarkHighContrast = Color(0xFF0D0C00)
val secondaryDarkHighContrast = Color(0xFFACFFF6)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFF7DD1C9)
val onSecondaryContainerDarkHighContrast = Color(0xFF000E0D)
val tertiaryDarkHighContrast = Color(0xFFE6F1FF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF95C8F6)
val onTertiaryContainerDarkHighContrast = Color(0xFF000C18)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF14140C)
val onBackgroundDarkHighContrast = Color(0xFFE6E2D5)
val surfaceDarkHighContrast = Color(0xFF14140C)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF49473A)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF4F0DE)
val outlineVariantDarkHighContrast = Color(0xFFC6C3B2)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE5E3D6)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF4D4A00)
val surfaceDimDarkHighContrast = Color(0xFF14140C)
val surfaceBrightDarkHighContrast = Color(0xFF515047)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF202018)
val surfaceContainerDarkHighContrast = Color(0xFF313128)
val surfaceContainerHighDarkHighContrast = Color(0xFF3C3C33)
val surfaceContainerHighestDarkHighContrast = Color(0xFF48473E)
















